spring:
  application:
    name: GarageManagementSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/garage_db
    username: postgres
    password: 1111
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false
    check-template-location: false

server:
  port: 8080
  servlet:
    context-path: /api/v1